create table
  public.accounts (
    customer_id bigint generated by default as identity,
    name text not null,
    email text not null,
    password text not null,
    date_of_birth date not null,
    created_at timestamp with time zone not null default now(),
    constraint accounts_pkey primary key (customer_id)
  ) tablespace pg_default;

  create table
  public.sellers (
    seller_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    verification boolean not null,
    constraint sellers_pkey primary key (seller_id),
    constraint sellers_seller_id_fkey foreign key (seller_id) references accounts (customer_id)
  ) tablespace pg_default;

  create table
  public.shoe_listings ? (
    shop_id bigint generated by default as identity,
    shoe_id bigint not null,
    quantity bigint not null,
    price bigint not null,
    brand text not null,
    color text not null,
    size bigint not null,
    style text not null,
    created_at timestamp with time zone not null default now(),
    constraint shoe_listings ? _pkey primary key (shop_id, shoe_id),
    constraint shoe_listings ? _shop_id_fkey foreign key (shop_id) references shops (shop_id)
  ) tablespace pg_default;

  create table
  public.shops (
    shop_id bigint generated by default as identity,
    seller_id bigint not null,
    store_name text not null,
    created_at timestamp with time zone not null default now(),
    constraint shops_pkey primary key (shop_id, seller_id),
    constraint shops_seller_id_key unique (seller_id),
    constraint shops_shop_id_key unique (shop_id),
    constraint shops_seller_id_fkey foreign key (seller_id) references sellers (seller_id)
  ) tablespace pg_default;

  create table
  public.test_listings (
    listing_id bigint generated by default as identity,
    shop_id bigint not null,
    shoe_id bigint not null,
    quantity bigint not null,
    price bigint not null,
    created_at timestamp with time zone not null default now(),
    constraint test - listings_pkey primary key (listing_id),
    constraint test_listings_shoe_id_fkey foreign key (shoe_id) references test_shoes (shoe_id),
    constraint test_listings_shop_id_fkey foreign key (shop_id) references shops (shop_id)
  ) tablespace pg_default;

  create table
  public.test_shoes (
    shoe_id bigint generated by default as identity,
    brand text not null,
    color text not null,
    size bigint not null,
    style text not null,
    created_at timestamp with time zone not null default now(),
    constraint test - shoes_pkey primary key (shoe_id)
  ) tablespace pg_default;

  create table
  public.test_shops (
    shop_id bigint generated by default as identity,
    customer_id bigint not null,
    store_name text not null,
    verified boolean not null default false,
    created_at timestamp with time zone not null default now(),
    constraint test - shops_pkey primary key (shop_id),
    constraint test_shops_customer_id_fkey foreign key (customer_id) references accounts (customer_id)
  ) tablespace pg_default;

INSERT INTO sellers (verification)
VALUES (FALSE);