create table
  public.cart_items (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    listing_id bigint not null,
    cart_id bigint not null,
    quantity integer not null,
    constraint cart_items_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.carts (
    cart_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    user_id bigint not null,
    constraint carts_pkey primary key (cart_id),
    constraint carts_user_id_fkey foreign key (user_id) references users (user_id)
  ) tablespace pg_default;

create table
  public.listings (
    listing_id bigint generated by default as identity,
    shop_id bigint not null,
    shoe_id bigint not null,
    price bigint not null,
    created_at timestamp with time zone not null default now(),
    size integer not null,
    transaction_id bigint not null,
    condition text not null,
    age / gender text not null,
    constraint test - listings_pkey primary key (listing_id),
    constraint listings_shoe_id_fkey foreign key (shoe_id) references shoes (shoe_id),
    constraint listings_shop_id_fkey foreign key (shop_id) references shops (shop_id),
    constraint listings_transaction_id_fkey foreign key (transaction_id) references transactions (id)
  ) tablespace pg_default;

create table
  public.listings (
    listing_id bigint generated by default as identity,
    shop_id bigint not null,
    shoe_id bigint not null,
    price bigint not null,
    created_at timestamp with time zone not null default now(),
    size integer not null,
    transaction_id bigint not null,
    condition text not null,
    age / gender text not null,
    constraint test - listings_pkey primary key (listing_id),
    constraint listings_shoe_id_fkey foreign key (shoe_id) references shoes (shoe_id),
    constraint listings_shop_id_fkey foreign key (shop_id) references shops (shop_id),
    constraint listings_transaction_id_fkey foreign key (transaction_id) references transactions (id)
  ) tablespace pg_default;

create table
  public.shoe_inventory_ledger (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    quantity integer not null,
    shop_id bigint not null,
    listing_id bigint not null,
    transaction_id bigint not null,
    constraint shoe_inventory_ledger_pkey primary key (id),
    constraint shoe_inventory_ledger_listing_id_fkey foreign key (listing_id) references listings (listing_id),
    constraint shoe_inventory_ledger_shop_id_fkey foreign key (shop_id) references shops (shop_id),
    constraint shoe_inventory_ledger_transaction_id_fkey foreign key (transaction_id) references transactions (id)
  ) tablespace pg_default;

create table
  public.shoes (
    shoe_id bigint generated by default as identity,
    brand text not null,
    color text not null,
    style text not null,
    created_at timestamp with time zone not null default now(),
    transaction_id bigint not null,
    constraint test - shoes_pkey primary key (shoe_id),
    constraint shoes_transaction_id_fkey foreign key (transaction_id) references transactions (id)
  ) tablespace pg_default;

create table
  public.shop_balance_ledger (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    balance bigint not null,
    shop_id bigint not null,
    constraint shop_balance_ledger_pkey primary key (id),
    constraint shop_balance_ledger_shop_id_fkey foreign key (shop_id) references shops (shop_id)
  ) tablespace pg_default;

create table
  public.shops (
    shop_id bigint generated by default as identity,
    user_id bigint not null,
    store_name text not null,
    created_at timestamp with time zone not null default now(),
    verified boolean null default false,
    constraint shops_pkey primary key (shop_id),
    constraint shops_seller_id_key unique (user_id),
    constraint shops_shop_id_key unique (shop_id)
  ) tablespace pg_default;

create table
  public.transactions (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    description text null,
    tag text not null,
    constraint transactions_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.users (
    user_id bigint generated by default as identity,
    name text not null,
    email text not null,
    password text not null,
    created_at timestamp with time zone not null default now(),
    constraint users_pkey primary key (user_id)
  ) tablespace pg_default;