import sqlalchemy
import os
import dotenv
from faker import Faker
import numpy as np

def database_connection_url():
    dotenv.load_dotenv()
    DB_USER = os.environ.get("POSTGRES_USER", "postgres")
    DB_PASSWD = os.environ.get("POSTGRES_PASSWORD", "postgres")
    DB_SERVER = os.environ.get("POSTGRES_SERVER", "127.0.0.1")
    DB_PORT = os.environ.get("POSTGRES_PORT", 54322)
    DB_NAME = os.environ.get("POSTGRES_DB", "postgres")

    return f"postgresql://{DB_USER}:{DB_PASSWD}@{DB_SERVER}:{DB_PORT}/{DB_NAME}"

# Create a new DB engine based on our connection string
engine = sqlalchemy.create_engine(database_connection_url(), use_insertmanyvalues=True)

with engine.begin() as conn:
    conn.execute(sqlalchemy.text("""
   
    DROP TABLE IF EXISTS users;
                                 
    create table
    public.users (
        user_id bigint generated by default as identity,
        name text not null,
        email text not null,
        password text not null,
        created_at timestamp with time zone not null default now(),
        constraint users_pkey primary key (user_id),
        constraint users_email_key unique (email),
        constraint users_password_key unique (password)
    ) tablespace pg_default;

    """))
    
    # populate initial posting categories
    # for category in categories:    
    #     conn.execute(sqlalchemy.text("""
    #     INSERT INTO category (category_name) VALUES (:category_name);
    #     """), {"category_name": category})

# num_users = 10
# fake = Faker()
# posts_sample_distribution = np.random.default_rng().negative_binomial(0.04, 0.01, num_users)
# category_sample_distribution = np.random.choice([1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
#                                                  num_users,
#                                                 p=[0.1, 0.05, 0.1, 0.3, 0.05, 0.05, 0.05, 0.05, 0.15, 0.1])
# total_posts = 0

# create fake posters with fake names and birthdays
fake = Faker()
with engine.begin() as conn:
    print("creating fake users...")
    posts = []
    for i in range(10000):
        #if (i % 10 == 0):
            #print(i)
        
        name = fake.first_name()
        email = fake.unique.email()
        password = fake.unique.password(length=5)
        #device_type = fake.random_element(elements=('Android', 'iOS', 'Web'))
        

        poster_id = conn.execute(sqlalchemy.text(
            """
            INSERT INTO users (name, email, password) 
            VALUES (:name, :email, :password) RETURNING user_id;
            """
        ), {"name": name, "email": email, "password": password }).scalar_one();

    #     num_posts = posts_sample_distribution[i]
    #     likes_sample_distribution = np.random.default_rng().negative_binomial(0.8, 0.0001, num_posts)  
    #     for j in range(num_posts):
    #         total_posts += 1
    #         posts.append({
    #             "title": fake.sentence(),
    #             "content": fake.text(),
    #             "poster_id": poster_id,
    #             "category_id": category_sample_distribution[i].item(),
    #             "visible": fake.boolean(75),
    #             "created_at": fake.date_time_between(start_date='-5y', end_date='now', tzinfo=None),
    #             "likes": likes_sample_distribution[j].item(),
    #             "nsfw": fake.boolean(10)
    #         })

    # if posts:
    #     conn.execute(sqlalchemy.text("""
    #     INSERT INTO posts (title, content, poster_id, category_id, visible, created_at) 
    #     VALUES (:title, :content, :poster_id, :category_id, :visible, :created_at);
    #     """), posts)

    # print("total posts: ", total_posts)